version: 2
jobs:
  one:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:38:b0:7f:91:f6:77:b7:70:ab:81:5e:1b:78:b2:29"
