version: 2
jobs:
  one:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
dependencies:
    override:
        - sudo pip install azurecli
deployment:
  prod:
    branch: master
    commands:
      - azure app service sync /home/ubuntu/CircleCiTesting app service://phptestcircleciwebapp --delete
